// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKotg15yCNAVEYGwloJ7FTZdbjvxYtoFM',
    appId: '1:766753306156:android:564fd62a12b2744f9e0389',
    messagingSenderId: '766753306156',
    projectId: 'caksiz-hyzmat-c23d3',
    storageBucket: 'caksiz-hyzmat-c23d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD81U3UEw_MrRKEio_r5hidHTTN1ZwEMqw',
    appId: '1:766753306156:ios:6a71121ff0080bd59e0389',
    messagingSenderId: '766753306156',
    projectId: 'caksiz-hyzmat-c23d3',
    storageBucket: 'caksiz-hyzmat-c23d3.firebasestorage.app',
    androidClientId: '766753306156-ign2dsebaa5d2vfimv0vcdufejambvla.apps.googleusercontent.com',
    iosClientId: '766753306156-iq1optgci6qsleuku5sv0macir5vidtg.apps.googleusercontent.com',
    iosBundleId: 'com.caksizhyzmat.app',
  );
}
